# Generated by Django 3.1.7 on 2021-02-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('fav_movies', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('members', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('website_url', models.URLField()),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.people')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('event_title', models.CharField(max_length=100)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.people')),
            ],
        ),
    ]
